// Comprehensive list of crew roles by department
// Includes all roles from crew templates (film, commercial, documentary, episodic, music video, photoshoot)

export const DEFAULT_ROLES_BY_DEPARTMENT: Record<string, string[]> = {
  camera: [
    'Director of Photography',
    'Camera Operator',
    '1st AC (Focus Puller)',
    '1st AC',
    '2nd AC (Clapper Loader)',
    'DIT (Digital Imaging Technician)',
    'DIT',
    'Steadicam Operator',
    'Drone Operator',
    'Camera PA',
    'B-Camera Operator',
    'B-Camera 1st AC',
  ],
  
  lighting_grip: [
    'Gaffer',
    'Best Boy Electric',
    'Electrician',
    'Board Operator',
    'Key Grip',
    'Best Boy Grip',
    'Dolly Grip',
    'Grip',
    'Swing',
  ],
  
  sound: [
    'Production Sound Mixer',
    'Boom Operator',
    'Sound Utility',
    'Playback Operator',
  ],
  
  art: [
    'Production Designer',
    'Art Director',
    'Assistant Art Director',
    'Set Decorator',
    'Lead Person',
    'Set Dresser',
    'Prop Master',
    'Assistant Prop Master',
    'Prop Builder',
    'Scenic Artist',
    'Construction Coordinator',
    'Carpenter',
    'Painter',
  ],
  
  wardrobe: [
    'Costume Designer',
    'Assistant Costume Designer',
    'Costume Supervisor',
    'Key Costumer',
    'Set Costumer',
    'Costume PA',
    'Stylist',
    'Assistant Stylist',
    'Wardrobe Assistant',
  ],
  
  makeup_hair: [
    'Key Makeup Artist',
    'Makeup Artist',
    'SFX Makeup Artist',
    'Key Hairstylist',
    'Hairstylist',
  ],
  
  production: [
    'Director',
    'Producer',
    'Executive Producer',
    'Co-Producer',
    'Co-Executive Producer',
    'Supervising Producer',
    'Showrunner',
    'Line Producer',
    'Production Manager',
    'Production Supervisor',
    'Production Coordinator',
    'Assistant Production Coordinator',
    '1st AD',
    '2nd AD',
    '2nd 2nd AD',
    'Production Assistant',
    'Set PA',
    'Office PA',
    'Script Supervisor',
    'Location Manager',
    'Assistant Location Manager',
    'Location Scout',
    'Location PA',
    'Creative Director',
    'Art Director',
    'Copywriter',
    'Account Executive',
    'Agency PA',
    'Field Producer',
    'Associate Producer',
    'Photographer',
    'Assistant Photographer',
    'Digital Tech',
    'Photo Assistant',
  ],
  
  post_production: [
    'Editor',
    'Assistant Editor',
    'Post Production Supervisor',
    'Post Production Coordinator',
    'Colorist',
    'VFX Supervisor',
    'VFX Producer',
    'VFX Coordinator',
    'Sound Designer',
    'Sound Editor',
    'Dialogue Editor',
    'Foley Artist',
    'Re-recording Mixer',
    'Composer',
    'Music Supervisor',
  ],
  
  transportation: [
    'Transportation Coordinator',
    'Transportation Captain',
    'Driver',
    'Picture Car Coordinator',
  ],
  
  catering: [
    'Caterer',
    'Craft Service',
  ],
  
  stunts: [
    'Stunt Coordinator',
    'Stunt Performer',
    'Stunt Rigger',
    'Safety Officer',
  ],
  
  vfx: [
    'VFX Supervisor',
    'VFX Producer',
    'VFX Coordinator',
    'On-Set VFX Supervisor',
    'VFX PA',
  ],
  
  other: [
    'Unit Publicist',
    'Still Photographer',
    'BTS Videographer',
    'Medic',
    'Security',
    'Animal Wrangler',
    'Fixer',
    'Translator',
    'Choreographer',
    'Dance Captain',
    'Retoucher',
  ],
};

