import type { BudgetTemplate } from '@doublecheck/schemas';

export const commercialTemplate = {
  name: 'Commercial Production Template',
  type: 'commercial',
  description: 'Comprehensive commercial/agency production budget template',
  isPublic: true,
  categories: [
    {
      category: {
        name: 'Agency/Client',
        order: 0,
        department: 'production',
        phase: 'pre-production',
        isSubtotal: false,
      },
      items: [
        { description: 'Executive Producer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Producer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Creative Director', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Art Director', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Copywriter', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Account Executive', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Agency PAs', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Client Travel & Accommodations', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Production',
        order: 1,
        department: 'production',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Director', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Line Producer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Production Manager', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Production Coordinator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: '1st AD', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: '2nd AD', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Production Assistants', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Production Office', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Production Insurance', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Camera',
        order: 2,
        department: 'camera',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Director of Photography', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Camera Operator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: '1st AC', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: '2nd AC', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'DIT', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Steadicam Operator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Drone Operator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Camera Package', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Lens Package', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Camera Accessories', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Media & Storage', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Lighting & Grip',
        order: 3,
        department: 'lighting_grip',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Gaffer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Best Boy Electric', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Electricians', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Key Grip', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Best Boy Grip', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Grips', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Lighting Package', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Grip Package', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Generator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Sound',
        order: 4,
        department: 'sound',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Production Sound Mixer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Boom Operator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Sound Package', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Wireless Microphones', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Art Department',
        order: 5,
        department: 'art',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Production Designer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Art Director', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Set Decorator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Set Dressers', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Prop Master', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Set Construction', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Set Dressing', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Props Purchase', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Props Rental', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Talent',
        order: 6,
        department: 'production',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Principal Talent', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Talent Agent Fees', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Talent Buyout', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Talent Usage Rights', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Background Talent', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Talent Casting', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Talent Fitting', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Wardrobe & Makeup',
        order: 7,
        department: 'wardrobe',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Costume Designer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Key Makeup Artist', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Makeup Artists', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Key Hairstylist', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Hairstylists', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Wardrobe Purchase', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Wardrobe Rental', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Makeup Supplies', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Hair Supplies', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Locations',
        order: 8,
        department: 'production',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Location Manager', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Location Scout', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Location Fees', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Location Permits', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Parking', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Security', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Location Insurance', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Transportation',
        order: 9,
        department: 'transportation',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Transportation Coordinator', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Picture Vehicles', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Production Vehicles', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Honeywagons', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Fuel', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Vehicle Rental', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Catering',
        order: 10,
        department: 'catering',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Caterer', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Craft Services', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Meals', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Craft Service Supplies', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Post-Production',
        order: 11,
        department: 'post_production',
        phase: 'post-production',
        isSubtotal: false,
      },
      items: [
        { description: 'Editor', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Assistant Editor', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Colorist', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Sound Mix', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, unit: 'days', quantity: 1 },
        { description: 'Music', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Music Licensing', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Graphics & Titles', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'VFX', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Post Facility', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Client Review Sessions', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Insurance & Legal',
        order: 12,
        department: 'production',
        phase: 'pre-production',
        isSubtotal: false,
      },
      items: [
        { description: 'Production Insurance', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Equipment Insurance', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Legal Clearances', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
        { description: 'Trademark/Copyright', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Contingency',
        order: 13,
        department: 'production',
        phase: 'production',
        isSubtotal: false,
      },
      items: [
        { description: 'Contingency (10%)', estimatedAmount: 0, actualAmount: 0, status: 'estimated' as const, quantity: 1 },
      ],
    },
  ],
};

