import type { BudgetTemplate } from '@/lib/schemas';

export const documentaryTemplate = {
  name: 'Documentary Template',
  type: 'documentary',
  description: 'Comprehensive documentary production budget template',
  isPublic: true,
  categories: [
    {
      category: {
        name: 'Production',
        order: 0,
        department: 'production',
        phase: 'production',
      },
      items: [
        { description: 'Director', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Co-Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Executive Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Manager', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Coordinator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Field Producer', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Associate Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Assistants', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Production Office', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Insurance', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Camera',
        order: 1,
        department: 'camera',
        phase: 'production',
      },
      items: [
        { description: 'Cinematographer', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Camera Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Camera Assistant', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Additional Camera Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Camera Package', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Lens Package', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Camera Accessories', estimatedAmount: 0 },
        { description: 'Media & Storage', estimatedAmount: 0 },
        { description: 'Camera Stabilization (Gimbal)', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Drone Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Drone Package', estimatedAmount: 0, unit: 'days', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Sound',
        order: 2,
        department: 'sound',
        phase: 'production',
      },
      items: [
        { description: 'Sound Recordist', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Boom Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Sound Package', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Wireless Lavaliers', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Sound Accessories', estimatedAmount: 0 },
        { description: 'Field Recording Equipment', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Lighting',
        order: 3,
        department: 'lighting_grip',
        phase: 'production',
      },
      items: [
        { description: 'Gaffer', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Lighting Package', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Battery Packs', estimatedAmount: 0 },
        { description: 'LED Panels', estimatedAmount: 0 },
        { description: 'Lighting Accessories', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Locations & Travel',
        order: 4,
        department: 'production',
        phase: 'production',
      },
      items: [
        { description: 'Location Manager', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Location Scout', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Location Fees', estimatedAmount: 0 },
        { description: 'Location Permits', estimatedAmount: 0 },
        { description: 'Travel - Airfare', estimatedAmount: 0 },
        { description: 'Travel - Accommodations', estimatedAmount: 0 },
        { description: 'Travel - Per Diem', estimatedAmount: 0 },
        { description: 'Ground Transportation', estimatedAmount: 0 },
        { description: 'Visa & Travel Documents', estimatedAmount: 0 },
        { description: 'Travel Insurance', estimatedAmount: 0 },
        { description: 'Parking & Tolls', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Archival & Stock Footage',
        order: 5,
        department: 'post_production',
        phase: 'post-production',
      },
      items: [
        { description: 'Archival Footage Licensing', estimatedAmount: 0 },
        { description: 'Stock Footage', estimatedAmount: 0 },
        { description: 'Photo Licensing', estimatedAmount: 0 },
        { description: 'Music Licensing', estimatedAmount: 0 },
        { description: 'News Archive Licensing', estimatedAmount: 0 },
        { description: 'Historical Footage', estimatedAmount: 0 },
        { description: 'Archival Research', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Post-Production',
        order: 6,
        department: 'post_production',
        phase: 'post-production',
      },
      items: [
        { description: 'Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Additional Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Post-Production Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Colorist', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Sound Designer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Sound Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Composer', estimatedAmount: 0 },
        { description: 'Music Recording', estimatedAmount: 0 },
        { description: 'Narration Recording', estimatedAmount: 0 },
        { description: 'Voiceover Talent', estimatedAmount: 0 },
        { description: 'Graphics & Titles', estimatedAmount: 0 },
        { description: 'Motion Graphics', estimatedAmount: 0 },
        { description: 'Animation', estimatedAmount: 0 },
        { description: 'Post-Production Facility', estimatedAmount: 0 },
        { description: 'Editing Equipment', estimatedAmount: 0 },
        { description: 'Storage & Media', estimatedAmount: 0 },
        { description: 'Transcription Services', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Insurance & Legal',
        order: 7,
        department: 'production',
        phase: 'pre-production',
      },
      items: [
        { description: 'Production Insurance', estimatedAmount: 0 },
        { description: 'Equipment Insurance', estimatedAmount: 0 },
        { description: 'Errors & Omissions', estimatedAmount: 0 },
        { description: 'Legal Fees', estimatedAmount: 0 },
        { description: 'Clearances', estimatedAmount: 0 },
        { description: 'Release Forms', estimatedAmount: 0 },
        { description: 'Rights & Permissions', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Contingency',
        order: 8,
        department: 'production',
        phase: 'production',
      },
      items: [
        { description: 'Contingency (10%)', estimatedAmount: 0 },
      ],
    },
  ],
};

