import type { BudgetTemplate } from '@/lib/schemas';

export const filmTemplate =  {
  name: 'Feature Film Template',
  type: 'film',
  description: 'Comprehensive feature film budget template with all major departments and line items',
  isPublic: true,
  categories: [
    {
      category: {
        name: 'Above The Line',
        order: 0,
        department: 'production',
        phase: 'pre-production',
      },
      items: [
        { description: 'Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Executive Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Co-Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Director', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Writer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Script Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Story Consultant', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Script Development', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Production',
        order: 1,
        department: 'production',
        phase: 'production',
      },
      items: [
        { description: 'Line Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Manager', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Coordinator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Production Coordinator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: '1st AD', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: '2nd AD', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: '2nd 2nd AD', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Assistants', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Set PA', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Office PA', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Production Office Rent', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Office Supplies & Equipment', estimatedAmount: 0 },
        { description: 'Production Insurance', estimatedAmount: 0 },
        { description: 'Workers Compensation', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Camera',
        order: 2,
        department: 'camera',
        phase: 'production',
      },
      items: [
        { description: 'Director of Photography', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Camera Operator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: '1st AC (Focus Puller)', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: '2nd AC (Clapper Loader)', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'DIT (Digital Imaging Technician)', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Steadicam Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Drone Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Camera PA', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Camera Package Rental', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Lens Package Rental', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Camera Accessories', estimatedAmount: 0 },
        { description: 'Filters & Matte Box', estimatedAmount: 0 },
        { description: 'Camera Support Equipment', estimatedAmount: 0 },
        { description: 'Media & Storage', estimatedAmount: 0 },
        { description: 'Camera Truck', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Lighting & Grip',
        order: 3,
        department: 'lighting_grip',
        phase: 'production',
      },
      items: [
        { description: 'Gaffer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Best Boy Electric', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Electricians', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Board Operator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Key Grip', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Best Boy Grip', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Dolly Grip', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Grips', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Swing', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Lighting Package Rental', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Grip Package Rental', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Generator Rental', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Cables & Distribution', estimatedAmount: 0 },
        { description: 'Grip Truck', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Lighting Truck', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Sound',
        order: 4,
        department: 'sound',
        phase: 'production',
      },
      items: [
        { description: 'Production Sound Mixer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Boom Operator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Sound Utility', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Playback Operator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Sound Package Rental', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Wireless Microphones', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Sound Accessories', estimatedAmount: 0 },
        { description: 'Sound Truck', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Art Department',
        order: 5,
        department: 'art',
        phase: 'production',
      },
      items: [
        { description: 'Production Designer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Art Director', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Art Director', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Set Decorator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Lead Person', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Set Dressers', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Prop Master', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Prop Master', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Prop Builder', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Scenic Artist', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Construction Coordinator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Carpenters', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Painters', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Set Construction', estimatedAmount: 0 },
        { description: 'Set Dressing', estimatedAmount: 0 },
        { description: 'Props Purchase', estimatedAmount: 0 },
        { description: 'Props Rental', estimatedAmount: 0 },
        { description: 'Art Department Supplies', estimatedAmount: 0 },
        { description: 'Art Truck', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Wardrobe',
        order: 6,
        department: 'wardrobe',
        phase: 'production',
      },
      items: [
        { description: 'Costume Designer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Costume Designer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Costume Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Key Costumer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Set Costumer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Costume PA', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Costume Rental', estimatedAmount: 0 },
        { description: 'Costume Purchase', estimatedAmount: 0 },
        { description: 'Costume Alterations', estimatedAmount: 0 },
        { description: 'Wardrobe Supplies', estimatedAmount: 0 },
        { description: 'Wardrobe Truck', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Hair & Makeup',
        order: 7,
        department: 'makeup_hair',
        phase: 'production',
      },
      items: [
        { description: 'Key Makeup Artist', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Makeup Artists', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'SFX Makeup Artist', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Key Hairstylist', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Hairstylists', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Makeup Supplies', estimatedAmount: 0 },
        { description: 'Hair Supplies', estimatedAmount: 0 },
        { description: 'Makeup Trailer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
      ],
    },
    {
      category: {
        name: 'Locations',
        order: 8,
        department: 'production',
        phase: 'production',
      },
      items: [
        { description: 'Location Manager', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Location Manager', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Location Scout', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Location PA', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Location Fees', estimatedAmount: 0 },
        { description: 'Location Permits', estimatedAmount: 0 },
        { description: 'Parking Fees', estimatedAmount: 0 },
        { description: 'Security', estimatedAmount: 0 },
        { description: 'Location Insurance', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Transportation',
        order: 9,
        department: 'transportation',
        phase: 'production',
      },
      items: [
        { description: 'Transportation Coordinator', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Picture Vehicles', estimatedAmount: 0 },
        { description: 'Production Vehicles', estimatedAmount: 0 },
        { description: 'Honeywagons (Restroom Trailers)', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Fuel', estimatedAmount: 0 },
        { description: 'Vehicle Rental', estimatedAmount: 0 },
        { description: 'Vehicle Insurance', estimatedAmount: 0 },
        { description: 'Parking', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Catering',
        order: 10,
        department: 'catering',
        phase: 'production',
      },
      items: [
        { description: 'Caterer', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Craft Services', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Meals', estimatedAmount: 0 },
        { description: 'Craft Service Supplies', estimatedAmount: 0 },
        { description: 'Catering Equipment', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Stunts',
        order: 11,
        department: 'stunts',
        phase: 'production',
      },
      items: [
        { description: 'Stunt Coordinator', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Stunt Performers', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Stunt Equipment', estimatedAmount: 0 },
        { description: 'Stunt Safety', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'VFX',
        order: 12,
        department: 'vfx',
        phase: 'production',
      },
      items: [
        { description: 'VFX Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'VFX Producer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'On-Set VFX Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'VFX Facility', estimatedAmount: 0 },
        { description: 'VFX Shots', estimatedAmount: 0 },
        { description: 'Motion Capture', estimatedAmount: 0 },
        { description: 'VFX Equipment', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Post-Production',
        order: 13,
        department: 'post_production',
        phase: 'post-production',
      },
      items: [
        { description: 'Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Assistant Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Additional Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Post-Production Supervisor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Colorist', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Sound Designer', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Sound Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'Dialogue Editor', estimatedAmount: 0, unit: 'weeks', quantity: 1 },
        { description: 'ADR Recording', estimatedAmount: 0 },
        { description: 'Foley', estimatedAmount: 0 },
        { description: 'Sound Mix', estimatedAmount: 0, unit: 'days', quantity: 1 },
        { description: 'Composer', estimatedAmount: 0 },
        { description: 'Music Recording', estimatedAmount: 0 },
        { description: 'Music Licensing', estimatedAmount: 0 },
        { description: 'Music Supervisor', estimatedAmount: 0 },
        { description: 'Post-Production Facility', estimatedAmount: 0 },
        { description: 'Editing Equipment', estimatedAmount: 0 },
        { description: 'Storage & Media', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Insurance & Legal',
        order: 14,
        department: 'production',
        phase: 'pre-production',
      },
      items: [
        { description: 'Production Insurance', estimatedAmount: 0 },
        { description: 'Equipment Insurance', estimatedAmount: 0 },
        { description: 'Errors & Omissions', estimatedAmount: 0 },
        { description: 'General Liability', estimatedAmount: 0 },
        { description: 'Legal Fees', estimatedAmount: 0 },
        { description: 'Clearances', estimatedAmount: 0 },
        { description: 'Trademark/Copyright', estimatedAmount: 0 },
      ],
    },
    {
      category: {
        name: 'Contingency',
        order: 15,
        department: 'production',
        phase: 'production',
      },
      items: [
        { description: 'Contingency (10%)', estimatedAmount: 0 },
      ],
    },
  ],
};

